#!/bin/sh
set -e

if [ ! -f ${TOOLBOX_PATH}/fft ] ; then

        echo "\$TOOLBOX_PATH is not set correctly!"
        exit 1
fi

CROP=0.
KRN=6
REG=24
LOW=20

while getopts "c:k:r:l:" opt; do
	case $opt in
	l)
		LOW=$OPTARG
	;;
	c)
		CROP=$OPTARG
	;;
	k)
		KRN=$OPTARG
	;;
	r)
		REG=$OPTARG
	;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
	;;
	esac
done

shift $((OPTIND-1))


if [ $# -lt 2 ] ; then

        echo "Usage: $0 <kspace> <maps>"
        exit 1
fi

export PATH=$TOOLBOX_PATH:$PATH

kspace=$(readlink -f "$1")
maps=$(readlink -f "$2")



#WORKDIR=$(mktemp -d)
# Mac: http://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
WORKDIR=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`
trap 'rm -rf "$WORKDIR"' EXIT
cd $WORKDIR

# create virtual conjugate channels
flip 7 $kspace tmp1
circshift 0 1 tmp1 tmp2
circshift 1 1 tmp2 tmp1
circshift 2 1 tmp1 tmp2
conj tmp2 vcs


# calibration
join 3 $kspace vcs both
ecalib -k${KRN} -r${REG} -S -c${CROP} both bsens val
rm both.*



# phase centering - rotate phase up to sign
COILS=$(cat bsens.hdr | tail -n1 | cut -d" " -f4)
HCOILS=$(expr ${COILS} \/ 2)
HCOILSM=$(expr ${COILS} \/ 2 - 1)
COILSM=$(expr ${COILS} - 1)

extract 3 0 ${HCOILSM} bsens maps1.coo
extract 3 ${HCOILS} ${COILSM} bsens maps2.coo
fmac -s8 maps1.coo maps2.coo rel.coo
cpyphs rel.coo ph.coo
spow 0.5 ph.coo phsqrt.coo
fmac -C maps1.coo phsqrt.coo sens

rm bsens.*



# extract low resolution phase
caldir ${LOW} $kspace sensLR
cpyphs sensLR ph
rm sensLR.*

scale  -- 1.i ph phi
join 4 ph phi phc
rm ph.* phi.*



# align sign
fmac -s8 -C sens phc tmp1.coo
creal tmp1.coo tmp2.coo
cpyphs tmp2.coo tmp1.coo
fmac sens tmp1.coo $maps



